### PR TITLE
Add dark theme

### LINKED ISSUE #28: Ensure icons appear correctly in dark mode
Reported to me by @coadler

### PR DESCRIPTION
**Pull request by nhooyr**
Closes #28

### CODE REVIEW

**Comment by coadler** [comment]
Still seems broken unless you haven't deployed

**Comment by nhooyr** [comment]
@coadler get a real dark theme going. I'm using the css:

```
@media (prefers-color-scheme: dark)
```

to switch it which works on browsers that support setting dark/light preference like Chrome on iOS/Safari on Mac/Safari on iOS, I'm sure there's a switch on chrome on linux too.

**Comment by nhooyr** [comment]
E.g. try on ur phone with dark theme enabled.

**Comment by coadler** [comment]
I'm using `chrome://flags/#enable-force-dark`

**Comment by nhooyr** [comment]
That's not setting a preference if the site supports it, that's forcing it. It's overriding all my CSS and fucking it up, I can't do anything afaik.

**Comment by coadler** [comment]
:cry:

**Pull request merged**
